//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 8/19/2014 12:22:56 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "IdsCategories.h" 


@implementation IdsCategories

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"clientCategoryID"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setClientCategoryID:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"serverCategoryID"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setServerCategoryID:[nodeContentValue intValue]];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<IdsCategories>" ];
    [nsString appendFormat:@"<clientCategoryID>%d</clientCategoryID>" , [self clientCategoryID]];
    [nsString appendFormat:@"<serverCategoryID>%d</serverCategoryID>" , [self serverCategoryID]];
    if (addNameWrap == YES)
        [nsString appendString:@"</IdsCategories>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.clientCategoryID = [decoder decodeInt32ForKey:@"clientCategoryID"];
        self.serverCategoryID = [decoder decodeInt32ForKey:@"serverCategoryID"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeInt32:self.clientCategoryID forKey:@"clientCategoryID"];
    [encoder encodeInt32:self.serverCategoryID forKey:@"serverCategoryID"];
}
-(id)copyWithZone:(NSZone *)zone {
    IdsCategories *finalCopy = [[[self class] allocWithZone: zone] init];
    
    finalCopy.clientCategoryID = self.clientCategoryID;
    
    finalCopy.serverCategoryID = self.serverCategoryID;
    
    return finalCopy;
}

@end
