//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 8/27/2014 3:43:10 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "IdsFiles.h" 


@implementation IdsFiles

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"clientFileID"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setClientFileID:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"serverFileID"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setServerFileID:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"fileType"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setFileType:[nodeContentValue intValue]];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<IdsFiles>" ];
    [nsString appendFormat:@"<clientFileID>%d</clientFileID>" , [self clientFileID]];
    [nsString appendFormat:@"<serverFileID>%d</serverFileID>" , [self serverFileID]];
    [nsString appendFormat:@"<fileType>%d</fileType>" , [self fileType]];
    if (addNameWrap == YES)
        [nsString appendString:@"</IdsFiles>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.clientFileID = [decoder decodeInt32ForKey:@"clientFileID"];
        self.serverFileID = [decoder decodeInt32ForKey:@"serverFileID"];
        self.fileType = [decoder decodeInt32ForKey:@"fileType"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeInt32:self.clientFileID forKey:@"clientFileID"];
    [encoder encodeInt32:self.serverFileID forKey:@"serverFileID"];
    [encoder encodeInt32:self.fileType forKey:@"fileType"];
}
-(id)copyWithZone:(NSZone *)zone {
    IdsFiles *finalCopy = [[[self class] allocWithZone: zone] init];
    
    finalCopy.clientFileID = self.clientFileID;
    
    finalCopy.serverFileID = self.serverFileID;
    
    finalCopy.fileType = self.fileType;
    
    return finalCopy;
}

@end
