//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 7/23/2014 1:02:39 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "iOSService_Enums.h"
#import "returnArrayIds.h"


@interface iOSService : NSObject
{
}
@property SoapProtocolVersion soapVersion;
@property BOOL allowAutoRedirect;
@property BOOL enableDecompression;
@property (nonatomic, copy) NSString *userAgent;
@property BOOL unsafeAuthenticatedConnectionSharing;
@property BOOL useDefaultCredentials;
@property (nonatomic, copy) NSString *connectionGroupName;
@property BOOL preAuthenticate;
@property (nonatomic, copy) NSString *url;
@property int timeout;
@property (nonatomic, assign) void(*targetAction)(id target,id sender,NSString* xml);
@property (nonatomic,assign) id actionDelegate;
@property (nonatomic, strong) NSURLConnection *wsConnection;
@property (nonatomic, strong) NSMutableData *webData;
@property (nonatomic, strong) NSError *error;
@property (nonatomic, strong) NSMutableDictionary *requestHeaders;
@property (nonatomic, copy)   NSString *eventName;

///Origin Return Type:NSString
-(void)autenticate:(NSString *)user :(NSString *)pass ;
///Origin Return Type:int
-(void)registerUser:(NSString *)user :(NSString *)pass ;
///Origin Return Type:returnArrayIds
-(void)categorySync:(NSString *)user :(NSString *)pass :(NSString *)clientCategoryID :(NSString *)serverCategoryID :(int)categoryType :(NSString *)categoryName :(NSString *)categoryColor :(NSString *)categoryStatus ;
///Origin Return Type:returnArrayIds
-(void)categoryShare:(NSString *)user :(NSString *)pass :(NSString *)categoryID :(NSString *)firendEmail ;
///Origin Return Type:returnArrayIds
-(void)itemSync:(NSString *)user :(NSString *)pass :(NSString *)categoryID :(NSString *)categoryName :(NSString *)categoryColor ;
-(id) initWithTarget:(id)target  AndAction:(void(*)(id target,id sender ,NSString* xml))action;
-(void) addTarget:(id)target AndAction:(void(*)(id target,id sender ,NSString* xml))action;
@end
