//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 8/19/2014 12:22:56 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "xpathquery.h"
#import "iOSService.h"
#import "inAllArray.h"
#import "RetAllArray.h"
#import "GetQueryArray.h"
#import "GetReturnArray.h"

#ifndef _Wsdl2CodeProxyDelegate
#define _Wsdl2CodeProxyDelegate
@protocol Wsdl2CodeProxyDelegate
//if service recieve an error this method will be called
-(void)proxyRecievedError:(NSException*)ex InMethod:(NSString*)method;
//proxy finished, (id)data is the object of the relevant method service
-(void)proxydidFinishLoadingData:(id)data InMethod:(NSString*)method;
@end
#endif

@interface iOSServiceProxy : NSObject
@property (nonatomic,assign) id<Wsdl2CodeProxyDelegate> proxyDelegate;
@property (nonatomic,copy)   NSString* url;
@property (nonatomic,retain) iOSService* service;

-(id)initWithUrl:(NSString*)url AndDelegate:(id<Wsdl2CodeProxyDelegate>)delegate;
///Origin Return Type:NSString
-(void)autenticate:(NSString *)user :(NSString *)pass ;
///Origin Return Type:int
-(void)registerUser:(NSString *)user :(NSString *)pass ;
///Origin Return Type:RetAllArray
-(void)syncAll:(inAllArray *)name ;
///Origin Return Type:GetReturnArray
-(void)checkUpdates:(GetQueryArray *)name ;
///Origin Return Type:RetAllArray
-(void)categoryShare:(NSString *)user :(NSString *)pass :(int)serverCategoryID :(NSString *)firendEmail ;
@end
