//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 7/8/2014 1:36:55 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "XPathQuery.h"
#import "iOSService.h"
#import "returnArrayIds.h"

#ifndef _Wsdl2CodeProxyDelegate
#define _Wsdl2CodeProxyDelegate
@protocol Wsdl2CodeProxyDelegate
//if service recieve an error this method will be called
-(void)proxyRecievedError:(NSException*)ex InMethod:(NSString*)method;
//proxy finished, (id)data is the object of the relevant method service
-(void)proxydidFinishLoadingData:(id)data InMethod:(NSString*)method;
@end
#endif

@interface iOSServiceProxy : NSObject
@property (nonatomic,assign) id<Wsdl2CodeProxyDelegate> proxyDelegate;
@property (nonatomic,copy)   NSString* url;
@property (nonatomic,retain) iOSService* service;

-(id)initWithUrl:(NSString*)url AndDelegate:(id<Wsdl2CodeProxyDelegate>)delegate;
///Origin Return Type:NSString
-(void)autenticate:(NSString *)user :(NSString *)pass ;
///Origin Return Type:int
-(void)registerUser:(NSString *)user :(NSString *)pass ;
///Origin Return Type:returnArrayIds
-(void)categoryAdd:(NSString *)user :(NSString *)pass :(NSString *)categoryID :(int)categoryType :(NSString *)categoryName :(NSString *)categoryColor ;
///Origin Return Type:returnArrayIds
-(void)categoryEdit:(NSString *)user :(NSString *)pass :(NSString *)categoryID :(NSString *)categoryName :(NSString *)categoryColor ;
///Origin Return Type:returnArrayIds
-(void)categoryDelete:(NSString *)user :(NSString *)pass :(NSString *)categoryID ;
///Origin Return Type:returnArrayIds
-(void)categoryShare:(NSString *)user :(NSString *)pass :(NSString *)categoryID :(NSString *)firendEmail ;
@end
