//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 7/8/2014 1:19:42 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "returnArrayIds.h" 


@implementation returnArrayIds

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"serverID"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setServerID:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"clientID"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setClientID:[nodeContentValue intValue]];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<returnArrayIds>" ];
    [nsString appendFormat:@"<serverID>%d</serverID>" , [self serverID]];
    [nsString appendFormat:@"<clientID>%d</clientID>" , [self clientID]];
    if (addNameWrap == YES)
        [nsString appendString:@"</returnArrayIds>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.serverID = [decoder decodeInt32ForKey:@"serverID"];
        self.clientID = [decoder decodeInt32ForKey:@"clientID"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeInt32:self.serverID forKey:@"serverID"];
    [encoder encodeInt32:self.clientID forKey:@"clientID"];
}
-(id)copyWithZone:(NSZone *)zone {
    returnArrayIds *finalCopy = [[[self class] allocWithZone: zone] init];
    
    finalCopy.serverID = self.serverID;
    
    finalCopy.clientID = self.clientID;
    
    return finalCopy;
}

@end
