//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.0
// Date Of Creation: 5/23/2014 4:12:21 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "NSData+Base64.h"


@interface Reminder : NSObject
{
}
@property int reminderID;
@property int categoryID;
@property (nonatomic, copy) NSString *eventName;
@property (nonatomic, copy) NSString *eventAlarm;
@property (nonatomic, copy) NSString *eventNote;
@property (nonatomic, copy) NSString *eventRecurring;
@property (nonatomic, strong) NSData *reminderPhoto;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
